
// This file has been generated by the GUI designer. Do not modify.
namespace Clonebit
{
	public partial class SettingsWindow
	{
		private global::Gtk.Table mainTable;

		private global::Gtk.Frame otherSettingsFrame;

		private global::Gtk.Alignment alignement2;

		private global::Gtk.Table otherSettingsTable;

		private global::Gtk.Button applyButton;

		private global::Gtk.Entry NFSEntry;

		private global::Gtk.Label NFSLabel;

		private global::Gtk.Entry privateKeyEntry;

		private global::Gtk.Label privateKeyLabel;

		private global::Gtk.Label otherSettingsLabel;

		private global::Gtk.Frame stationFrame;

		private global::Gtk.Alignment alignement1;

		private global::Gtk.Table stationTable;

		private global::Gtk.Button addButton;

		private global::Gtk.Entry addressEntry;

		private global::Gtk.Button modifyButton;

		private global::Gtk.Button resetButton;

		private global::Gtk.ComboBox stationComboBox;

		private global::Gtk.Label stationLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Clonebit.SettingsWindow
			this.Name = "Clonebit.SettingsWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Paramètres");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Clonebit.SettingsWindow.Gtk.Container+ContainerChild
			this.mainTable = new global::Gtk.Table(((uint)(2)), ((uint)(1)), false);
			this.mainTable.Name = "mainTable";
			this.mainTable.RowSpacing = ((uint)(6));
			this.mainTable.ColumnSpacing = ((uint)(6));
			// Container child mainTable.Gtk.Table+TableChild
			this.otherSettingsFrame = new global::Gtk.Frame();
			this.otherSettingsFrame.Name = "otherSettingsFrame";
			this.otherSettingsFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			this.otherSettingsFrame.LabelXalign = 0.5F;
			this.otherSettingsFrame.BorderWidth = ((uint)(10));
			// Container child otherSettingsFrame.Gtk.Container+ContainerChild
			this.alignement2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.alignement2.Name = "alignement2";
			this.alignement2.LeftPadding = ((uint)(15));
			this.alignement2.TopPadding = ((uint)(15));
			this.alignement2.RightPadding = ((uint)(15));
			this.alignement2.BottomPadding = ((uint)(15));
			// Container child alignement2.Gtk.Container+ContainerChild
			this.otherSettingsTable = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.otherSettingsTable.Name = "otherSettingsTable";
			this.otherSettingsTable.RowSpacing = ((uint)(6));
			this.otherSettingsTable.ColumnSpacing = ((uint)(6));
			// Container child otherSettingsTable.Gtk.Table+TableChild
			this.applyButton = new global::Gtk.Button();
			this.applyButton.CanFocus = true;
			this.applyButton.Name = "applyButton";
			this.applyButton.UseUnderline = true;
			this.applyButton.Label = global::Mono.Unix.Catalog.GetString("Appliquer");
			global::Gtk.Image w1 = new global::Gtk.Image();
			this.applyButton.Image = w1;
			this.otherSettingsTable.Add(this.applyButton);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.otherSettingsTable[this.applyButton]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child otherSettingsTable.Gtk.Table+TableChild
			this.NFSEntry = new global::Gtk.Entry();
			this.NFSEntry.CanFocus = true;
			this.NFSEntry.Name = "NFSEntry";
			this.NFSEntry.Text = global::Mono.Unix.Catalog.GetString("/media/shared_folder/");
			this.NFSEntry.IsEditable = true;
			this.NFSEntry.InvisibleChar = '●';
			this.otherSettingsTable.Add(this.NFSEntry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.otherSettingsTable[this.NFSEntry]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child otherSettingsTable.Gtk.Table+TableChild
			this.NFSLabel = new global::Gtk.Label();
			this.NFSLabel.Name = "NFSLabel";
			this.NFSLabel.Xalign = 0F;
			this.NFSLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Chemin du NFS :</b>");
			this.NFSLabel.UseMarkup = true;
			this.otherSettingsTable.Add(this.NFSLabel);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.otherSettingsTable[this.NFSLabel]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child otherSettingsTable.Gtk.Table+TableChild
			this.privateKeyEntry = new global::Gtk.Entry();
			this.privateKeyEntry.CanFocus = true;
			this.privateKeyEntry.Name = "privateKeyEntry";
			this.privateKeyEntry.Text = global::Mono.Unix.Catalog.GetString("/home/user/.ssh/id_ed25519");
			this.privateKeyEntry.IsEditable = true;
			this.privateKeyEntry.InvisibleChar = '●';
			this.otherSettingsTable.Add(this.privateKeyEntry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.otherSettingsTable[this.privateKeyEntry]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child otherSettingsTable.Gtk.Table+TableChild
			this.privateKeyLabel = new global::Gtk.Label();
			this.privateKeyLabel.Name = "privateKeyLabel";
			this.privateKeyLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Chemin de la clé privée :</b>");
			this.privateKeyLabel.UseMarkup = true;
			this.otherSettingsTable.Add(this.privateKeyLabel);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.otherSettingsTable[this.privateKeyLabel]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(0));
			this.alignement2.Add(this.otherSettingsTable);
			this.otherSettingsFrame.Add(this.alignement2);
			this.otherSettingsLabel = new global::Gtk.Label();
			this.otherSettingsLabel.Name = "otherSettingsLabel";
			this.otherSettingsLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Autres paramètres</b>");
			this.otherSettingsLabel.UseMarkup = true;
			this.otherSettingsFrame.LabelWidget = this.otherSettingsLabel;
			this.mainTable.Add(this.otherSettingsFrame);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.mainTable[this.otherSettingsFrame]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child mainTable.Gtk.Table+TableChild
			this.stationFrame = new global::Gtk.Frame();
			this.stationFrame.Name = "stationFrame";
			this.stationFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			this.stationFrame.LabelXalign = 0.5F;
			this.stationFrame.BorderWidth = ((uint)(10));
			// Container child stationFrame.Gtk.Container+ContainerChild
			this.alignement1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.alignement1.Name = "alignement1";
			this.alignement1.LeftPadding = ((uint)(15));
			this.alignement1.TopPadding = ((uint)(15));
			this.alignement1.RightPadding = ((uint)(15));
			this.alignement1.BottomPadding = ((uint)(15));
			// Container child alignement1.Gtk.Container+ContainerChild
			this.stationTable = new global::Gtk.Table(((uint)(2)), ((uint)(4)), false);
			this.stationTable.Name = "stationTable";
			this.stationTable.RowSpacing = ((uint)(6));
			this.stationTable.ColumnSpacing = ((uint)(6));
			// Container child stationTable.Gtk.Table+TableChild
			this.addButton = new global::Gtk.Button();
			this.addButton.CanFocus = true;
			this.addButton.Name = "addButton";
			this.addButton.UseUnderline = true;
			this.addButton.Label = global::Mono.Unix.Catalog.GetString("Ajouter une station");
			this.stationTable.Add(this.addButton);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.stationTable[this.addButton]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.RightAttach = ((uint)(4));
			// Container child stationTable.Gtk.Table+TableChild
			this.addressEntry = new global::Gtk.Entry();
			this.addressEntry.CanFocus = true;
			this.addressEntry.Name = "addressEntry";
			this.addressEntry.IsEditable = true;
			this.addressEntry.MaxLength = 15;
			this.addressEntry.InvisibleChar = '●';
			this.stationTable.Add(this.addressEntry);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.stationTable[this.addressEntry]));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child stationTable.Gtk.Table+TableChild
			this.modifyButton = new global::Gtk.Button();
			this.modifyButton.CanFocus = true;
			this.modifyButton.Name = "modifyButton";
			this.modifyButton.UseUnderline = true;
			this.modifyButton.Label = global::Mono.Unix.Catalog.GetString("Modifier");
			global::Gtk.Image w12 = new global::Gtk.Image();
			this.modifyButton.Image = w12;
			this.stationTable.Add(this.modifyButton);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.stationTable[this.modifyButton]));
			w13.LeftAttach = ((uint)(3));
			w13.RightAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child stationTable.Gtk.Table+TableChild
			this.resetButton = new global::Gtk.Button();
			this.resetButton.CanFocus = true;
			this.resetButton.Name = "resetButton";
			this.resetButton.UseUnderline = true;
			this.resetButton.Label = global::Mono.Unix.Catalog.GetString("Réinitialiser");
			global::Gtk.Image w14 = new global::Gtk.Image();
			this.resetButton.Image = w14;
			this.stationTable.Add(this.resetButton);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.stationTable[this.resetButton]));
			w15.LeftAttach = ((uint)(2));
			w15.RightAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child stationTable.Gtk.Table+TableChild
			this.stationComboBox = global::Gtk.ComboBox.NewText();
			this.stationComboBox.Name = "stationComboBox";
			this.stationTable.Add(this.stationComboBox);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.stationTable[this.stationComboBox]));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.alignement1.Add(this.stationTable);
			this.stationFrame.Add(this.alignement1);
			this.stationLabel = new global::Gtk.Label();
			this.stationLabel.Name = "stationLabel";
			this.stationLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Configuration réseau des stations de duplication</b>");
			this.stationLabel.UseMarkup = true;
			this.stationFrame.LabelWidget = this.stationLabel;
			this.mainTable.Add(this.stationFrame);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.mainTable[this.stationFrame]));
			w19.YOptions = ((global::Gtk.AttachOptions)(0));
			this.Add(this.mainTable);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 640;
			this.DefaultHeight = 347;
			this.Show();
			this.stationComboBox.Changed += new global::System.EventHandler(this.OnStationComboBoxChanged);
			this.applyButton.Clicked += new global::System.EventHandler(this.OnApplyButtonClicked);
		}
	}
}
