
// This file has been generated by the GUI designer. Do not modify.
namespace Clonebit
{
	public partial class LoginPage
	{
		private global::Gtk.Table mainTable;

		private global::Gtk.Frame loginFrame;

		private global::Gtk.Alignment alignement1;

		private global::Gtk.Table loginTable;

		private global::Gtk.Entry databaseEntry;

		private global::Gtk.Label databaseLabel;

		private global::Gtk.Button loginButton;

		private global::Gtk.Entry passwordEntry;

		private global::Gtk.Label passwordLabel;

		private global::Gtk.Entry usernameEntry;

		private global::Gtk.Label usernameLabel;

		private global::Gtk.Label loginLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Clonebit.LoginPage
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 1280;
			this.HeightRequest = 720;
			this.Name = "Clonebit.LoginPage";
			// Container child Clonebit.LoginPage.Gtk.Container+ContainerChild
			this.mainTable = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.mainTable.Name = "mainTable";
			this.mainTable.RowSpacing = ((uint)(6));
			this.mainTable.ColumnSpacing = ((uint)(6));
			// Container child mainTable.Gtk.Table+TableChild
			this.loginFrame = new global::Gtk.Frame();
			this.loginFrame.Name = "loginFrame";
			this.loginFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			this.loginFrame.LabelXalign = 0.5F;
			// Container child loginFrame.Gtk.Container+ContainerChild
			this.alignement1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.alignement1.Name = "alignement1";
			this.alignement1.LeftPadding = ((uint)(15));
			this.alignement1.TopPadding = ((uint)(15));
			this.alignement1.RightPadding = ((uint)(15));
			this.alignement1.BottomPadding = ((uint)(15));
			// Container child alignement1.Gtk.Container+ContainerChild
			this.loginTable = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
			this.loginTable.Name = "loginTable";
			this.loginTable.RowSpacing = ((uint)(6));
			this.loginTable.ColumnSpacing = ((uint)(6));
			// Container child loginTable.Gtk.Table+TableChild
			this.databaseEntry = new global::Gtk.Entry();
			this.databaseEntry.CanFocus = true;
			this.databaseEntry.Name = "databaseEntry";
			this.databaseEntry.Text = global::Mono.Unix.Catalog.GetString("duplication");
			this.databaseEntry.IsEditable = true;
			this.databaseEntry.InvisibleChar = '●';
			this.loginTable.Add(this.databaseEntry);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.loginTable[this.databaseEntry]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child loginTable.Gtk.Table+TableChild
			this.databaseLabel = new global::Gtk.Label();
			this.databaseLabel.Name = "databaseLabel";
			this.databaseLabel.Xalign = 0F;
			this.databaseLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Base de données :</b>");
			this.databaseLabel.UseMarkup = true;
			this.loginTable.Add(this.databaseLabel);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.loginTable[this.databaseLabel]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child loginTable.Gtk.Table+TableChild
			this.loginButton = new global::Gtk.Button();
			this.loginButton.CanFocus = true;
			this.loginButton.Name = "loginButton";
			this.loginButton.UseUnderline = true;
			this.loginButton.Label = global::Mono.Unix.Catalog.GetString("Se connecter");
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-dialog-authentication", global::Gtk.IconSize.Menu);
			this.loginButton.Image = w3;
			this.loginTable.Add(this.loginButton);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.loginTable[this.loginButton]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.RightAttach = ((uint)(2));
			// Container child loginTable.Gtk.Table+TableChild
			this.passwordEntry = new global::Gtk.Entry();
			this.passwordEntry.CanFocus = true;
			this.passwordEntry.Name = "passwordEntry";
			this.passwordEntry.IsEditable = true;
			this.passwordEntry.Visibility = false;
			this.passwordEntry.InvisibleChar = '●';
			this.loginTable.Add(this.passwordEntry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.loginTable[this.passwordEntry]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			// Container child loginTable.Gtk.Table+TableChild
			this.passwordLabel = new global::Gtk.Label();
			this.passwordLabel.Name = "passwordLabel";
			this.passwordLabel.Xalign = 0F;
			this.passwordLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Mot-de-passe :</b>");
			this.passwordLabel.UseMarkup = true;
			this.loginTable.Add(this.passwordLabel);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.loginTable[this.passwordLabel]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child loginTable.Gtk.Table+TableChild
			this.usernameEntry = new global::Gtk.Entry();
			this.usernameEntry.CanFocus = true;
			this.usernameEntry.Name = "usernameEntry";
			this.usernameEntry.IsEditable = true;
			this.usernameEntry.InvisibleChar = '●';
			this.loginTable.Add(this.usernameEntry);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.loginTable[this.usernameEntry]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			// Container child loginTable.Gtk.Table+TableChild
			this.usernameLabel = new global::Gtk.Label();
			this.usernameLabel.Name = "usernameLabel";
			this.usernameLabel.Xalign = 0F;
			this.usernameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Nom d\'utilisateur :</b>");
			this.usernameLabel.UseMarkup = true;
			this.loginTable.Add(this.usernameLabel);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.loginTable[this.usernameLabel]));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(0));
			this.alignement1.Add(this.loginTable);
			this.loginFrame.Add(this.alignement1);
			this.loginLabel = new global::Gtk.Label();
			this.loginLabel.Name = "loginLabel";
			this.loginLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Connexion à Clonebit</b>");
			this.loginLabel.UseMarkup = true;
			this.loginFrame.LabelWidget = this.loginLabel;
			this.mainTable.Add(this.loginFrame);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.mainTable[this.loginFrame]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(1));
			w11.YOptions = ((global::Gtk.AttachOptions)(1));
			this.Add(this.mainTable);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.loginButton.Clicked += new global::System.EventHandler(this.OnLoginButtonClicked);
		}
	}
}
